services:

  mariadb:
    container_name: mariadb
    build:
      context: "./requirements/mariadb"
      args:
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'